name: Build Game for Android
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
      - name: Compile
        run: haxelib run lime setup android
                haxelib run lime build android
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: AndroidBuild
          path: export/release/android/build/Release-android/*.apk
          if-no-files-found: error
